<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-OrderSplitter-92fd1435-0e14-46d4-bbe3-0bf91c6e7ea2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Messaging.Shared\Messaging.Shared.csproj" />
  </ItemGroup>
</Project>
